import type { CharacterSheetData, SpellSlotLevel } from './types'

const skills = (
  list: { name: string; proficient: boolean; bonus: number }[],
) => list

function spellSlotsInitial(): SpellSlotLevel[] {
  const base = Array.from({ length: 9 }, () => ({ max: 0, used: 0 }))
  base[0] = { max: 4, used: 0 }
  base[1] = { max: 2, used: 0 }
  return base
}

function spellSlotsEmpty(): SpellSlotLevel[] {
  return Array.from({ length: 9 }, () => ({ max: 0, used: 0 }))
}

function neutralSkills(names: string[]) {
  return names.map((name) => ({ name, proficient: false, bonus: 0 }))
}

function emptyAbilities(): CharacterSheetData['abilities'] {
  return {
    str: {
      key: 'str',
      label: 'Strength',
      score: 10,
      modifier: 0,
      saveProficient: false,
      saveBonus: 0,
      skills: neutralSkills(['Athletics']),
    },
    dex: {
      key: 'dex',
      label: 'Dexterity',
      score: 10,
      modifier: 0,
      saveProficient: false,
      saveBonus: 0,
      skills: neutralSkills(['Acrobatics', 'Sleight of Hand', 'Stealth']),
    },
    con: {
      key: 'con',
      label: 'Constitution',
      score: 10,
      modifier: 0,
      saveProficient: false,
      saveBonus: 0,
      skills: [],
    },
    int: {
      key: 'int',
      label: 'Intelligence',
      score: 10,
      modifier: 0,
      saveProficient: false,
      saveBonus: 0,
      skills: neutralSkills([
        'Arcana',
        'History',
        'Investigation',
        'Nature',
        'Religion',
      ]),
    },
    wis: {
      key: 'wis',
      label: 'Wisdom',
      score: 10,
      modifier: 0,
      saveProficient: false,
      saveBonus: 0,
      skills: neutralSkills([
        'Animal Handling',
        'Insight',
        'Medicine',
        'Perception',
        'Survival',
      ]),
    },
    cha: {
      key: 'cha',
      label: 'Charisma',
      score: 10,
      modifier: 0,
      saveProficient: false,
      saveBonus: 0,
      skills: neutralSkills(['Deception', 'Intimidation', 'Performance', 'Persuasion']),
    },
  }
}

/**
 * Blank sheet: empty strings, numeric fields at 0, no weapons/spells/equipment rows.
 * Ability scores default to 10 / +0 so the skill list structure matches a normal sheet.
 */
export const emptyCharacterSheet: CharacterSheetData = {
  name: '',
  species: '',
  className: '',
  subclass: '',
  background: '',
  level: 1,
  xp: 0,
  ac: 0,
  hpCurrent: 0,
  hpMax: 0,
  hpTemp: 0,
  hitDiceSpent: 0,
  hitDiceMax: 0,
  hitDiceDie: 'd8',
  deathSuccesses: 0,
  deathFailures: 0,
  proficiencyBonus: 0,
  inspiration: false,
  initiative: 0,
  speed: 0,
  size: '',
  passivePerception: 0,
  abilities: emptyAbilities(),
  weapons: [],
  classFeatures: '',
  narrative: '',
  speciesTraits: '',
  feats: [],
  featNotes: '',
  armorTraining: {
    light: false,
    medium: false,
    heavy: false,
    shields: false,
  },
  weaponProficiencies: {
    simple: false,
    martial: false,
    other: '',
  },
  toolProficiencies: '',
  spellcasting: {
    ability: '',
    modifier: 0,
    spellSaveDc: 0,
    spellAttackBonus: 0,
  },
  spellSlotsByLevel: spellSlotsEmpty(),
  spells: [],
  appearance: '',
  personalityTraits: '',
  alignment: '',
  languages: [],
  equipment: [],
  attunement: [
    { name: '', attuned: false },
    { name: '', attuned: false },
    { name: '', attuned: false },
  ],
  coins: {
    cp: 0,
    sp: 0,
    ep: 0,
    gp: 0,
    pp: 0,
  },
}

/** Fresh tab / default storage: blank sheet (not the sample character). */
export function createNewCharacterTemplate(): CharacterSheetData {
  return structuredClone(emptyCharacterSheet)
}

export const sampleCharacterSheet: CharacterSheetData = {
  name: 'Sehet',
  species: 'Sea Elf',
  speciesFiveEToolsRef: 'Sea Elf|MPMM',
  className: 'Druid',
  classNameFiveEToolsRef: 'Druid|PHB',
  subclass: 'Circle of the Stars',
  background: 'Shipwright',
  level: 3,
  xp: 900,
  ac: 14,
  hpCurrent: 15,
  hpMax: 15,
  hpTemp: 0,
  hitDiceSpent: 0,
  hitDiceMax: 3,
  hitDiceDie: 'd8',
  deathSuccesses: 0,
  deathFailures: 0,
  proficiencyBonus: 2,
  inspiration: false,
  initiative: 2,
  speed: 30,
  size: 'Medium',
  passivePerception: 17,
  abilities: {
    str: {
      key: 'str',
      label: 'Strength',
      score: 8,
      modifier: -1,
      saveProficient: false,
      saveBonus: -1,
      skills: skills([{ name: 'Athletics', proficient: false, bonus: -1 }]),
    },
    dex: {
      key: 'dex',
      label: 'Dexterity',
      score: 14,
      modifier: 2,
      saveProficient: false,
      saveBonus: 2,
      skills: skills([
        { name: 'Acrobatics', proficient: false, bonus: 2 },
        { name: 'Sleight of Hand', proficient: false, bonus: 2 },
        { name: 'Stealth', proficient: false, bonus: 2 },
      ]),
    },
    con: {
      key: 'con',
      label: 'Constitution',
      score: 14,
      modifier: 2,
      saveProficient: true,
      saveBonus: 4,
      skills: [],
    },
    int: {
      key: 'int',
      label: 'Intelligence',
      score: 10,
      modifier: 0,
      saveProficient: false,
      saveBonus: 0,
      skills: skills([
        { name: 'Arcana', proficient: true, bonus: 2 },
        { name: 'History', proficient: false, bonus: 0 },
        { name: 'Investigation', proficient: false, bonus: 0 },
        { name: 'Nature', proficient: true, bonus: 2 },
        { name: 'Religion', proficient: false, bonus: 0 },
      ]),
    },
    wis: {
      key: 'wis',
      label: 'Wisdom',
      score: 17,
      modifier: 3,
      saveProficient: true,
      saveBonus: 5,
      skills: skills([
        { name: 'Animal Handling', proficient: false, bonus: 3 },
        { name: 'Insight', proficient: true, bonus: 5 },
        { name: 'Medicine', proficient: false, bonus: 3 },
        { name: 'Perception', proficient: true, bonus: 7 },
        { name: 'Survival', proficient: true, bonus: 5 },
      ]),
    },
    cha: {
      key: 'cha',
      label: 'Charisma',
      score: 12,
      modifier: 1,
      saveProficient: false,
      saveBonus: 1,
      skills: skills([
        { name: 'Deception', proficient: false, bonus: 1 },
        { name: 'Intimidation', proficient: false, bonus: 1 },
        { name: 'Performance', proficient: false, bonus: 1 },
        { name: 'Persuasion', proficient: false, bonus: 1 },
      ]),
    },
  },
  weapons: [
    {
      id: 'w1',
      name: '+1 Moon Sickle',
      attackBonus: 6,
      diceCount: 1,
      diceSize: 'd4',
      damageType: 'Slashing',
      notes: 'Druid focus',
      fiveEToolsRef: '+1 Moon Sickle|TCE',
    },
  ],
  classFeatures: `Wild Shape — 2 / short rest (CR ½, no flying)

Circle of the Stars — Starry Form: bonus action; swap Archer / Chalice / Dragon constellations.`,
  narrative: `Shipwright background: repairs at sea, salt-stained hands, talks to tide pools like colleagues.`,
  speciesTraits: `Campaign: coastal shoal clan; speaks Primordial (Aquian dialect).`,
  feats: [],
  featNotes: '',
  armorTraining: {
    light: true,
    medium: true,
    heavy: false,
    shields: true,
  },
  weaponProficiencies: {
    simple: true,
    martial: true,
    other: '',
  },
  toolProficiencies: `Carpenter's tools, Water vehicles`,

  spellcasting: {
    ability: 'Wisdom',
    modifier: 5,
    spellSaveDc: 15,
    spellAttackBonus: 7,
  },
  spellSlotsByLevel: spellSlotsInitial(),
  spells: [
    {
      id: 's1',
      cantrip: false,
      level: 1,
      name: 'Speak with Animals',
      castingTime: '1 A',
      range: 'Self',
      concentration: false,
      ritual: true,
      material: false,
      notes: 'V, S — 10 min',
    },
    {
      id: 's2',
      cantrip: false,
      level: 1,
      name: 'Charm Person',
      castingTime: '1 A',
      range: '30 ft',
      concentration: false,
      ritual: false,
      material: false,
      notes: 'V, S',
    },
    {
      id: 's3',
      cantrip: false,
      level: 1,
      name: 'Cure Wounds',
      castingTime: '1 A',
      range: 'Touch',
      concentration: false,
      ritual: false,
      material: false,
      notes: 'V, S — 1d8 + mod',
    },
    {
      id: 's4',
      cantrip: false,
      level: 1,
      name: 'Healing Word',
      castingTime: '1 BA',
      range: '60 ft',
      concentration: false,
      ritual: false,
      material: false,
      notes: 'V',
    },
    {
      id: 's5',
      cantrip: false,
      level: 1,
      name: 'Thunderwave',
      castingTime: '1 A',
      range: 'Self (15 ft cube)',
      concentration: false,
      ritual: false,
      material: false,
      notes: 'V, S',
    },
    {
      id: 's6',
      cantrip: false,
      level: 1,
      name: 'Find Familiar',
      castingTime: '1 H',
      range: '10 ft',
      concentration: false,
      ritual: true,
      material: true,
      notes: 'V, S, M (10 gp)',
    },
    {
      id: 's7',
      cantrip: false,
      level: 1,
      name: 'Guiding Bolt',
      castingTime: '1 A',
      range: '120 ft',
      concentration: false,
      ritual: false,
      material: false,
      notes: 'V, S — 4d6 radiant',
    },
    {
      id: 's8',
      cantrip: true,
      level: 0,
      name: 'Guidance',
      castingTime: '1 A',
      range: 'Touch',
      concentration: true,
      ritual: false,
      material: false,
      notes: 'V, S — Conc., up to 1 min',
    },
    {
      id: 's9',
      cantrip: true,
      level: 0,
      name: 'Starry Wisp',
      castingTime: '1 A',
      range: '60 ft',
      concentration: false,
      ritual: false,
      material: false,
      notes: 'V, S',
      fiveEToolsRef: 'Starry Wisp|XPHB',
    },
    {
      id: 's10',
      cantrip: true,
      level: 0,
      name: 'Spare the Dying',
      castingTime: '1 A',
      range: 'Touch',
      concentration: false,
      ritual: false,
      material: false,
      notes: 'V, S',
    },
    {
      id: 's11',
      cantrip: false,
      level: 2,
      name: 'Aid',
      castingTime: '1 A',
      range: '30 ft',
      concentration: false,
      ritual: false,
      material: false,
      notes: 'V, S, M',
    },
    {
      id: 's12',
      cantrip: false,
      level: 2,
      name: 'Moonbeam',
      castingTime: '1 A',
      range: '120 ft',
      concentration: true,
      ritual: false,
      material: false,
      notes: 'V, S, M — Conc.',
    },
  ],

  appearance: `5'4" — 130 lbs`,
  personalityTraits: `• Mysteries of the deep
• Endless supply of cautionary tales
• Invention
• I will craft a boat that can ride any wave.
• I don't know when to throw something away.`,
  alignment: '',
  languages: [
    { id: 'lang-1', name: 'Common' },
    { id: 'lang-2', name: 'Primordial' },
    { id: 'lang-3', name: 'Druidic' },
  ],

  equipment: [
    {
      id: 'eq-1',
      name: "Carpenter's tools",
      quantity: 1,
      equipped: false,
      notes: '',
      goldGp: 0,
    },
    {
      id: 'eq-2',
      name: 'Herbalism kit',
      quantity: 1,
      equipped: false,
      notes: '',
      goldGp: 0,
    },
    {
      id: 'eq-3',
      name: "Explorer's pack",
      quantity: 1,
      equipped: false,
      notes: '',
      goldGp: 0,
    },
    {
      id: 'eq-4',
      name: 'Bedroll',
      quantity: 1,
      equipped: false,
      notes: '',
      goldGp: 0,
    },
    {
      id: 'eq-5',
      name: 'Hempen rope (50 ft)',
      quantity: 1,
      equipped: false,
      notes: '',
      goldGp: 0,
    },
    {
      id: 'eq-6',
      name: 'Hide armor',
      quantity: 1,
      equipped: true,
      notes: '',
      goldGp: 0,
    },
    {
      id: 'eq-7',
      name: 'Shield',
      quantity: 1,
      equipped: true,
      notes: '',
      goldGp: 0,
    },
    {
      id: 'eq-8',
      name: 'Sickle',
      quantity: 1,
      equipped: false,
      notes: '',
      goldGp: 0,
    },
    {
      id: 'eq-9',
      name: 'Quarterstaff',
      quantity: 1,
      equipped: false,
      notes: '',
      goldGp: 0,
    },
  ],
  attunement: [
    { name: '', attuned: false },
    { name: '', attuned: false },
    { name: '', attuned: false },
  ],
  coins: {
    cp: 0,
    sp: 0,
    ep: 0,
    gp: 19,
    pp: 0,
  },
}
